"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[palette]
  yellow_gold = '#FFB900'
  red = '#E06C75'

[transient_prompt]
  template = '# '
  foreground_templates = [
    '{{ if eq .Code 0 }}p:yellow_gold{{ end }}',
    '{{ if gt .Code 0 }}p:red{{ end }}'
  ]

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#45F1C2'
    template = ' {{ .UserName }} on'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#0CA0D8'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#14A5AE'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    powerline_symbol = ''

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground_templates = [
      '{{ if eq .Code 0 }}#B8FF75{{ end }}',
      '{{ if gt .Code 0 }}p:red{{ end }}'
    ]

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 1000

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#F3C267'
    template = '  {{ .CurrentDate | date .Format }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#CD5E42'
    template = ' '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '# '
    foreground_templates = [
      '{{ if eq .Code 0 }}p:yellow_gold{{ end }}',
      '{{ if gt .Code 0 }}p:red{{ end }}'
    ]
